# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - tlmgr install index
  
matrix:
  include:
  - r: devel
  - r: release

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'covr::codecov(type="all", line_exclusions="R/zzz.R")'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
